language: node_js

node_js:
  - "10"
  - "11"
  - "12"

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run lint
  - npm run test:cover
  - npm run build

after_success:
  - node_modules/.bin/ocular coverage/clover.xml
