language: node_js

node_js:
  - "10"
  - "11"
  - "12"

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run lint
  - npm run test:cover
  - npm run build

after_success:
  - node_modules/.bin/ocular coverage/clover.xml

deploy:
  provider: npm
  skip_cleanup: true
  email: alejandrocelaya@gmail.com
  api_key:
    secure: KJe+C3ubJChEJqLqKVasGA9efmo6h5BK4jyJKa6AlwvTp1F6nhaWB+lJCwU+32dprEmX1ZVqQpMDCk2QnLYwjvNPR2xB+JZsZVkyOCue9qJgIQypiow8yYt/L9k+PL4BtEmxu9iBfM580D4KJls9v2dcyEvnrl6zv2QS25h0Q68ZfwrMLA34eJuLU/9wlVpTPnyWkPwYg4fyFY80mPXvIiML2cVxCtwaibsxTLHWrQx5WMa6mmsJXxWKcx87qhzJVZhsxbbYDQBwI6a4udSgqs5ZI7Nl3NnFdouQYdS4gTCdtKvQEc6pb/cRDAcGyE1uMrYRx6lvdyCjsjMzS1R1RXn66IleKs/xaukWI8HrjxG/XufzzWHWqIxN6pb7jZMAEG3FCh+bDCmNNKRElCp1/KmXwMpp4m7eFAP4RGp/Du8YwQy5uYv7tV8gdn6vFSS3QKtH9V0nQTikX89zfkEWZ6G/pWX0SGerpucIJ8d05TrgTOP5CHbilhO2BXd0HZH4cMg1fKe1uXX7+LbsokaTsUw05/mqGe3s06yVb312nyr2q93hzFjiNHUX6rBzTzvoaJjVOg7xRnBPZ7fa2t1OGD9lO2zHIlawGzN1yOmAj/L6RAkA9ENG8PiqSIFt0kcTy6WMSV3ONgns3HOSmZxiPTLM00NK/DAcdbxbkHwqPVk=
  on:
    tags: true
    node_js: '12'
